### ISSUE TITLE
Balanced market V2G can lead to frequent charging/discharging

### ISSUE THREAD

**Issue by stefansc1** [rl-institut/spice_ev#32]
SoC jumps around optimal value because of always using maximum charging/discharging power in V2G simulation.

**Comment by jakobgemassmer** [comment]
![grafik](https://user-images.githubusercontent.com/49757031/145806235-29e523ef-df70-4238-b596-1122a46b4215.png)

**Comment by jakobgemassmer** [comment]
![grafik](https://user-images.githubusercontent.com/49757031/146142804-77278a90-bd9e-42d7-b553-f9ac8f48665e.png)
[oszillieren.json.txt](https://github.com/rl-institut/spice_ev/files/7717279/oszillieren.json.txt)

**Comment by paulboehnke** [comment]
This issue is rooted in the fact that charging balanced to the desired SOC has the highest priority from the algorithms perspective. 
The images depict a situation that leads to rapid charging/discharging.

![IMG_1757 Large](https://user-images.githubusercontent.com/20053419/146230895-b68cca03-6448-412f-af1d-1bf4953c70ac.jpeg)

SOC < desired SOC: The cheapest time interval (B) is blocked for balanced charging. Therefore the discharging in the most expensive timesteps (21,22,23) is countered with a charging signal in the current timestep (1). This leads to a charging command that puts the vehicle over the desired SOC.

![IMG_1756 2 Large](https://user-images.githubusercontent.com/20053419/146230989-8fede024-a38f-455e-8340-fdb9adb2e3fb.jpeg)

SOC > desired SOC: If the SOC is larger than the desired SOC, the cheapest time interval (B) is not blocked for balanced charging. Therefore, the discharging in the most expensive interval (C) is countered with charging in the cheapest time interval (B). The current timestep (13) in the image gets a discharge signal putting the vehicle below the desired SOC. Why the current timestep always gets a discharging signal is another issue, I dont have time to write down just now.

Tried to fix this issue in #46
