### ISSUE TITLE
add example input data for "generate_from_download" and "generate_from_simbev"

### ISSUE THREAD

**Issue by Piranias** [rl-institut/spice_ev#67]
if the two generate scripts should stay in the repo it would be nice to add exemplary input files to the "example" folder, so we can a) test them and b) other people know how to use them.

**Comment by jakobgemassmer** [comment]
Hey @Piranias the "generate_from_download" does not need to stay in the repo. It is exclusively for the project, since it uses the measured data. We will maybe need it a few times to validate our simulation results, but I wouldn't be comfortable with providing examplary measured data.

"Generate_from_csv" however should stay, since this is more general. Can you add some examplary bus-data?

**Comment by Piranias** [comment]
> Hey @Piranias the "generate_from_download" does not need to stay in the repo. It is exclusively for the project, since it uses the measured data. We will maybe need it a few times to validate our simulation results, but I wouldn't be comfortable with providing examplary measured data.
> 
> "Generate_from_csv" however should stay, since this is more general. Can you add some examplary bus-data?

ok, and how about the generate_from_simbev? For the 'generate_from_csv' there is already exemplary input

**Comment by jakobgemassmer** [comment]
Misread, "generate_from_simbev" also should stay, since simbev is open source as well. I will talk to Tim to add an example. SimBEV had some major changes, so we need to check, if we need to adjust our generate script accordingly first.
