### ISSUE TITLE
Long driving time leading to SoC/margin-error

### ISSUE THREAD

**Issue by jakobgemassmer** [rl-institut/spice_ev#80]
A very long driving time (see "max_driving") leads to an error that the soc of a vehicle is below the desired_soc, even though the margin is set to 1.
Is this intended? This could lead to failures in simulations with very long driving times, like busses.
![grafik](https://user-images.githubusercontent.com/49757031/154945689-8fe6636c-ae6e-415c-bf20-1b880183cb62.png)

![grafik](https://user-images.githubusercontent.com/49757031/154945354-f7bd99a9-9008-449c-8e0e-665411b7f6bd.png)
JSON with failure: [test_fail.json.txt](https://github.com/rl-institut/spice_ev/files/8108742/test_fail.json.txt)

If "max_driving" is lowered to 16h, the simulation does not fail. The output shows no sign of why the soc can not be reached.
![grafik](https://user-images.githubusercontent.com/49757031/154945199-5b137339-a57d-4d22-9c1d-2c8207ffb8af.png)
JSON without failure: [test.json.txt](https://github.com/rl-institut/spice_ev/files/8108740/test.json.txt)

**Comment by Piranias** [comment]
i get a similar error. Although in my case the margin is reset to it's default value after a while. It is read out from the kwags / options in the beginning, but later it appears to be the default value again. Maybe because the strategy class is initialized without kwags at some point? screenshop of my simulate.cfg and the debugger at the point where the assert is failing in strategy.py

![error_margin](https://user-images.githubusercontent.com/44803304/155304431-7b56e1b6-4b02-44bc-a071-d2b80a2290d1.png)
